version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: express-app

  app:
    image: asheldkr/express-app-devops
    container_name: express-app
    restart: unless-stopped
    ports:
      - 8080:8080
